// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCaCISvU85o77m836QfBDrpLWXmlUunSM',
    appId: '1:20529786309:web:d0ae520231b2e1a0662fac',
    messagingSenderId: '20529786309',
    projectId: 'kv-app-542a2',
    authDomain: 'kv-app-542a2.firebaseapp.com',
    storageBucket: 'kv-app-542a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcW4XPCA-0rgVR33f06wBjXptueOEecEQ',
    appId: '1:20529786309:android:4afb14f903542de7662fac',
    messagingSenderId: '20529786309',
    projectId: 'kv-app-542a2',
    storageBucket: 'kv-app-542a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRA7hXz7UKeBCO2n4GvhkEiJgPGlLB3iU',
    appId: '1:611775071009:ios:a7e5013636682f88747460',
    messagingSenderId: '611775071009',
    projectId: 'kv-app-db6ba',
    storageBucket: 'kv-app-db6ba.firebasestorage.app',
    iosBundleId: 'com.example.kisanverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRA7hXz7UKeBCO2n4GvhkEiJgPGlLB3iU',
    appId: '1:611775071009:ios:a7e5013636682f88747460',
    messagingSenderId: '611775071009',
    projectId: 'kv-app-db6ba',
    storageBucket: 'kv-app-db6ba.firebasestorage.app',
    iosBundleId: 'com.example.kisanverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ95eN58c6wAazC17dAtnEu0aN2g6Lrhg',
    appId: '1:611775071009:web:44f5e17576cc6a63747460',
    messagingSenderId: '611775071009',
    projectId: 'kv-app-db6ba',
    authDomain: 'kv-app-db6ba.firebaseapp.com',
    storageBucket: 'kv-app-db6ba.firebasestorage.app',
    measurementId: 'G-1P37FQ2MF9',
  );

}